In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv',low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [3]:
df_movies = df_movies[['imdb_title_id', 'title','year',
                       'genre','country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

# concat()

## Concatenate vertically

To concatenate vertically (along the rows) we should have columns in common between the 2 dataframes

In [4]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'H'],
                   'age': [40, 21, 19, 24]})

In [6]:
# axis = 0 (default) (means vertical concat)
pd.concat([df1, df2], axis=0, ignore_index = True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  H   24

## Exercise

In [7]:
# extract a 50% sample of the original dataframe (df_movies)
df_sample = df_movies.sample(frac = 0.5)

In [10]:
# shape of dataframes that we'll concatenate
print(df_sample.shape)
print(df_movies.shape)

(42928, 5)
(85855, 5)

In [14]:
# concatenate and df_movies and df_sample (vertically along the rows)
df_concat_vertically = pd.concat([df_movies, df_sample], axis = 0)

In [15]:
# shape
df_concat_vertically.shape

(128783, 5)

## Concatenate horizontally

To concatenate horizontally (along the columns) we should have a common index between the 2 dataframes

In [16]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})

In [17]:
pd.concat([df1, df2], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

## Exercise

In [19]:
# shape of dataframes that we'll concatenate
print(df_movies.shape)
print(df_ratings.shape)

(85855, 5)
(85855, 3)

In [28]:
df_movies.set_index('imdb_title_id', inplace = True)
df_ratings.set_index('imdb_title_id', inplace = True)

In [29]:
# concatenate df_movies and df_ratings on 'imdb_title_id' (horizontally along the columns)
df_concat_horizontally = pd.concat([df_movies, df_ratings], axis = 1)

In [30]:
# shape
df_concat_horizontally.shape

(85855, 6)

In [31]:
df_concat_horizontally.head()

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9