In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [3]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year',
                       'genre', 'country']]

df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

# merge()

In [4]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician',
                            'Accountant', 'Developer']})

In [8]:
print(df1)
print(df2)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

# Inner join

In [13]:
df_inner_join = df1.merge(df2, on='id', how='inner')
df_inner_join

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [12]:
# shape
print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)

(4, 2)
(4, 2)
(2, 3)

## Exercise

In [15]:
# merge df_movies and df_ratings (inner join) [default = inner]
df_movies.merge(df_ratings, on='imdb_title_id', how='inner')

pd.merge(df_movies, df_ratings, )

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

# Outer join (Full)

In [6]:
df_outer_join = df1.merge(df2, on='id', how='outer')

In [8]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='outer').shape)

(4, 2)
(4, 2)
(6, 3)

## Exercise

In [9]:
# merge df_movies and df_ratings (outer join)
df_movies.merge(df_ratings, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

# Exclusive Outer join (Exclusive Full join)

In [11]:
df1.merge(df2, on = 'id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [12]:
# indicator=True
df1.merge(df2, on = 'id', how='outer', indicator = True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [15]:
# query
df1.merge(df2, on = 'id', how='outer',
          indicator = True).query("_merge=='left_only' or _merge=='right_only'")

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [16]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='outer',
          indicator=True).query("_merge=='left_only' or _merge=='right_only'").shape)

(4, 2)
(4, 2)
(4, 4)

## Exercise

In [17]:
# merge df_movies and df_ratings
df_movies.merge(df_ratings, on='imdb_title_id', how='outer', 
                indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

# Left join

In [18]:
df1.merge(df2, on='id', how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

## Exercise

In [20]:
# extraact 50% sample of the df_movies dataframe
df_movies_sample = df_movies.sample(frac = 0.5)
df_movies_sample

,imdb_title_id,title,year,genre,country
52314,tt10054876,Zero Distance,2020,Thriller,Saudi Arabia
67233,tt2419576,Aadhalal Kadhal Seiveer,2013,Romance,India
57452,tt1372687,Crnci,2009,"Crime, Drama, War",Croatia
10625,tt0054709,"Porci, geishe e marinai",1961,"Action, Comedy, Crime",Japan
61712,tt1757671,Anwar,2010,"Action, Drama, Thriller",India
...,...,...,...,...,...
6130,tt0041285,Dear Mr. Prohack,1949,"Comedy, Romance",UK
15197,tt0067749,Shinbone Alley,1970,"Animation, Comedy, Fantasy",USA
22903,tt0092099,Top Gun,1986,"Action, Drama",USA
51253,tt0892904,White on Rice,2009,Comedy,USA
78245,tt5639536,Super Detention,2016,"Action, Comedy, Family",Canada

In [21]:
# merge df_movies_sample and df_ratings (left join)
df_left = df_movies_sample.merge(df_ratings, on='imdb_title_id', how='left')

In [22]:
# shape
print(df_movies_sample.shape)
print(df_ratings.shape)
print(df_left.shape)

(42928, 5)
(85855, 3)
(42928, 7)

# Exclusive Left join

In [23]:
# indicator = True
df1.merge(df2, on='id', how='outer', indicator=True)

  id  age           job     _merge
0  A   30           NaN  left_only
1  B   23           NaN  left_only
2  C   25        Doctor       both
3  D   22  Statistician       both

In [24]:
# query
df1.merge(df2, on='id', how='left',
          indicator=True).query("_merge == 'left_only'")

  id  age  job     _merge
0  A   30  NaN  left_only
1  B   23  NaN  left_only

In [25]:
# Left join [other way]
pd.merge(df_movies, df_ratings.sample(frac=.5),
         on='imdb_title_id', how='left').shape

(85855, 7)

## Exercise

In [26]:
# make a copy of the df_movies dataframe
df_movies_2 = df_movies.copy()

In [28]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_movies_2.index:
    if index < 1000:
        df_movies_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [29]:
df_movies_2

,imdb_title_id,title,year,genre,country
0,tt1234567890,Miss Jerry,1894,Romance,USA
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt1234567890,Cleopatra,1912,"Drama, History",USA
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [32]:
# merge df_movies_2 and df_ratings (exclusive left join)
df_exclusive_left = df_movies_2.merge(df_ratings, on='imdb_title_id', how='left',
                  indicator=True).query("_merge == 'left_only'")

In [33]:
# shape
print(df_movies_2.shape)
print(df_ratings.shape)
print(df_exclusive_left.shape)

(85855, 5)
(85855, 3)
(1000, 8)

# Right join

In [5]:
df1.merge(df2, on='id', how='right')

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

## Exercise

In [6]:
# extract a 30% sample of the df_ratings dataframe
df_ratings_sample = df_ratings.sample(frac = 0.3)

In [9]:
# merge df_movies and df_ratings_sample (riht join)
df_right = df_movies.merge(df_ratings_sample, on = 'imdb_title_id',
                how = 'right')

In [10]:
# shape
print(df_movies.shape)
print(df_ratings_sample.shape)
print(df_right.shape)

(85855, 5)
(25756, 3)
(25756, 7)

# Exclusive Right join

In [11]:
# indicator = True
df1.merge(df2, on = 'id', how = 'outer',
         indicator = True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [13]:
# query
df1.merge(df2, on='id', how='outer',
          indicator=True).query("_merge == 'right_only'")

  id  age         job      _merge
4  E  NaN  Accountant  right_only
5  F  NaN   Developer  right_only

## Exercise

In [14]:
# make a copy of the df_ratings dataframe
df_ratings_2 = df_ratings.copy()

In [15]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_ratings_2.index:
    if index < 1000:
        df_ratings_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [17]:
# merge df_movies and df_ratings_2 (exclusive right join)
df_exclusive_right = df_movies.merge(df_ratings_2, on = 'imdb_title_id', how='outer',
               indicator = True).query("_merge == 'right_only'")

In [18]:
# shape
print(df_movies.shape)
print(df_ratings_2.shape)
print(df_exclusive_right.shape)

(85855, 5)
(85855, 3)
(1000, 8)